# 测试 全局表
spring:
  shardingsphere:
    datasource:
      names: ds1,ds2
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:55003/sharding_sphere?serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:55001/sharding_sphere?serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    sharding:
      tables:
        order_dic:
          #指定orders表里主键id生成策略
          key-generator:
            column: id
            type: SNOWFLAKE
      # 默认表分片策略为不分片
      default-table-strategy:
        none:
      # 指定全局表
      broadcast-tables: order_dic
    #打开sql输出日志
    props:
      sql:
        show: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml