spring:
  application:
    name: sharding-sphere
  profiles:
    active: d5




mybatis:
  mapper-locations: classpath:/mapper/*.xml
  # 开启驼峰命名映射
  configuration:
    map-underscore-to-camel-case: true